// 포켓몬 가오레 로스터 정의 (직접 큐레이션)
// id: 전국도감 번호 (기본 폼만 사용)
// rarity: C/B/A/S/SS — 출현율·포획률·등급 추첨에 사용
// courses: 출현 코스 ('grass'|'sea'|'cave'|'legend')
// evolvesTo: 진화 찬스 대상 (배열이면 랜덤 선택, 이브이용)
// moveOverride: 기술 자동 선정 대신 사용할 기술 id 2개

export const ROSTER = [
  // ===== 1세대 =====
  { id: 1, rarity: 'C', courses: ['grass'], evolvesTo: [2] },
  { id: 2, rarity: 'B', courses: ['grass'], evolvesTo: [3] },
  { id: 3, rarity: 'A', courses: ['grass'] },
  { id: 4, rarity: 'C', courses: ['cave'], evolvesTo: [5] },
  { id: 5, rarity: 'B', courses: ['cave'], evolvesTo: [6] },
  { id: 6, rarity: 'A', courses: ['cave'] },
  { id: 7, rarity: 'C', courses: ['sea'], evolvesTo: [8] },
  { id: 8, rarity: 'B', courses: ['sea'], evolvesTo: [9] },
  { id: 9, rarity: 'A', courses: ['sea'] },
  { id: 16, rarity: 'C', courses: ['grass'], evolvesTo: [17] },
  { id: 17, rarity: 'C', courses: ['grass'], evolvesTo: [18] },
  { id: 18, rarity: 'B', courses: ['grass'] },
  { id: 25, rarity: 'B', courses: ['grass'], evolvesTo: [26], moveOverride: [85, 98] },
  { id: 26, rarity: 'A', courses: ['grass'] },
  { id: 39, rarity: 'C', courses: ['grass'], evolvesTo: [40] },
  { id: 40, rarity: 'B', courses: ['grass'] },
  { id: 41, rarity: 'C', courses: ['cave'], evolvesTo: [42] },
  { id: 42, rarity: 'B', courses: ['cave'], evolvesTo: [169] },
  { id: 169, rarity: 'A', courses: ['cave'] },
  { id: 52, rarity: 'C', courses: ['grass'], evolvesTo: [53] },
  { id: 53, rarity: 'B', courses: ['grass'] },
  { id: 54, rarity: 'C', courses: ['sea'], evolvesTo: [55] },
  { id: 55, rarity: 'B', courses: ['sea'] },
  { id: 58, rarity: 'B', courses: ['cave'], evolvesTo: [59] },
  { id: 59, rarity: 'A', courses: ['cave'] },
  { id: 63, rarity: 'B', courses: ['cave'], evolvesTo: [64] },
  { id: 64, rarity: 'A', courses: ['cave'], evolvesTo: [65] },
  { id: 65, rarity: 'S', courses: ['cave'] },
  { id: 66, rarity: 'C', courses: ['cave'], evolvesTo: [67] },
  { id: 67, rarity: 'B', courses: ['cave'], evolvesTo: [68] },
  { id: 68, rarity: 'A', courses: ['cave'] },
  { id: 74, rarity: 'C', courses: ['cave'], evolvesTo: [75] },
  { id: 75, rarity: 'B', courses: ['cave'], evolvesTo: [76] },
  { id: 76, rarity: 'A', courses: ['cave'] },
  { id: 79, rarity: 'C', courses: ['sea'], evolvesTo: [80] },
  { id: 80, rarity: 'B', courses: ['sea'] },
  { id: 92, rarity: 'B', courses: ['cave'], evolvesTo: [93] },
  { id: 93, rarity: 'A', courses: ['cave'], evolvesTo: [94] },
  { id: 94, rarity: 'S', courses: ['cave'] },
  { id: 95, rarity: 'B', courses: ['cave'], evolvesTo: [208] },
  { id: 208, rarity: 'A', courses: ['cave'] },
  { id: 104, rarity: 'C', courses: ['cave'], evolvesTo: [105] },
  { id: 105, rarity: 'B', courses: ['cave'] },
  { id: 123, rarity: 'A', courses: ['grass'], evolvesTo: [212] },
  { id: 127, rarity: 'A', courses: ['grass'] },
  { id: 129, rarity: 'C', courses: ['sea'], evolvesTo: [130] },
  { id: 130, rarity: 'S', courses: ['sea'] },
  { id: 131, rarity: 'S', courses: ['sea'] },
  { id: 133, rarity: 'B', courses: ['grass'], evolvesTo: [134, 135, 136, 196, 197, 470, 471, 700] },
  { id: 134, rarity: 'A', courses: ['sea'] },
  { id: 135, rarity: 'A', courses: ['grass'] },
  { id: 136, rarity: 'A', courses: ['cave'] },
  { id: 196, rarity: 'A', courses: ['grass'] },
  { id: 197, rarity: 'A', courses: ['cave'] },
  { id: 470, rarity: 'A', courses: ['grass'] },
  { id: 471, rarity: 'A', courses: ['sea'] },
  { id: 700, rarity: 'A', courses: ['grass'] },
  { id: 143, rarity: 'S', courses: ['grass'] },
  { id: 147, rarity: 'B', courses: ['sea'], evolvesTo: [148] },
  { id: 148, rarity: 'A', courses: ['sea'], evolvesTo: [149] },
  { id: 149, rarity: 'S', courses: ['sea'] },
  { id: 150, rarity: 'SS', courses: ['legend'] },
  { id: 151, rarity: 'SS', courses: ['legend'] },

  // ===== 2세대 =====
  { id: 152, rarity: 'C', courses: ['grass'], evolvesTo: [153] },
  { id: 153, rarity: 'B', courses: ['grass'], evolvesTo: [154] },
  { id: 154, rarity: 'A', courses: ['grass'] },
  { id: 155, rarity: 'C', courses: ['cave'], evolvesTo: [156] },
  { id: 156, rarity: 'B', courses: ['cave'], evolvesTo: [157] },
  { id: 157, rarity: 'A', courses: ['cave'] },
  { id: 158, rarity: 'C', courses: ['sea'], evolvesTo: [159] },
  { id: 159, rarity: 'B', courses: ['sea'], evolvesTo: [160] },
  { id: 160, rarity: 'A', courses: ['sea'] },
  { id: 179, rarity: 'C', courses: ['grass'], evolvesTo: [180] },
  { id: 180, rarity: 'B', courses: ['grass'], evolvesTo: [181] },
  { id: 181, rarity: 'A', courses: ['grass'] },
  { id: 212, rarity: 'S', courses: ['cave'] },
  { id: 214, rarity: 'A', courses: ['grass'] },
  { id: 246, rarity: 'B', courses: ['cave'], evolvesTo: [247] },
  { id: 247, rarity: 'A', courses: ['cave'], evolvesTo: [248] },
  { id: 248, rarity: 'S', courses: ['cave'] },
  { id: 243, rarity: 'SS', courses: ['legend'] },
  { id: 244, rarity: 'SS', courses: ['legend'] },
  { id: 245, rarity: 'SS', courses: ['legend'] },
  { id: 249, rarity: 'SS', courses: ['legend'] },
  { id: 250, rarity: 'SS', courses: ['legend'] },

  // ===== 3세대 =====
  { id: 252, rarity: 'C', courses: ['grass'], evolvesTo: [253] },
  { id: 253, rarity: 'B', courses: ['grass'], evolvesTo: [254] },
  { id: 254, rarity: 'A', courses: ['grass'] },
  { id: 255, rarity: 'C', courses: ['cave'], evolvesTo: [256] },
  { id: 256, rarity: 'B', courses: ['cave'], evolvesTo: [257] },
  { id: 257, rarity: 'A', courses: ['cave'] },
  { id: 258, rarity: 'C', courses: ['sea'], evolvesTo: [259] },
  { id: 259, rarity: 'B', courses: ['sea'], evolvesTo: [260] },
  { id: 260, rarity: 'A', courses: ['sea'] },
  { id: 280, rarity: 'B', courses: ['grass'], evolvesTo: [281] },
  { id: 281, rarity: 'A', courses: ['grass'], evolvesTo: [282] },
  { id: 282, rarity: 'S', courses: ['grass'] },
  { id: 304, rarity: 'B', courses: ['cave'], evolvesTo: [305] },
  { id: 305, rarity: 'A', courses: ['cave'], evolvesTo: [306] },
  { id: 306, rarity: 'S', courses: ['cave'] },
  { id: 359, rarity: 'A', courses: ['cave'] },
  { id: 371, rarity: 'B', courses: ['cave'], evolvesTo: [372] },
  { id: 372, rarity: 'A', courses: ['cave'], evolvesTo: [373] },
  { id: 373, rarity: 'S', courses: ['cave'] },
  { id: 374, rarity: 'B', courses: ['cave'], evolvesTo: [375] },
  { id: 375, rarity: 'A', courses: ['cave'], evolvesTo: [376] },
  { id: 376, rarity: 'S', courses: ['cave'] },
  { id: 382, rarity: 'SS', courses: ['legend'] },
  { id: 383, rarity: 'SS', courses: ['legend'] },
  { id: 384, rarity: 'SS', courses: ['legend'] },

  // ===== 4세대 =====
  { id: 387, rarity: 'C', courses: ['grass'], evolvesTo: [388] },
  { id: 388, rarity: 'B', courses: ['grass'], evolvesTo: [389] },
  { id: 389, rarity: 'A', courses: ['grass'] },
  { id: 390, rarity: 'C', courses: ['cave'], evolvesTo: [391] },
  { id: 391, rarity: 'B', courses: ['cave'], evolvesTo: [392] },
  { id: 392, rarity: 'A', courses: ['cave'] },
  { id: 393, rarity: 'C', courses: ['sea'], evolvesTo: [394] },
  { id: 394, rarity: 'B', courses: ['sea'], evolvesTo: [395] },
  { id: 395, rarity: 'A', courses: ['sea'] },
  { id: 403, rarity: 'C', courses: ['grass'], evolvesTo: [404] },
  { id: 404, rarity: 'B', courses: ['grass'], evolvesTo: [405] },
  { id: 405, rarity: 'A', courses: ['grass'] },
  { id: 443, rarity: 'B', courses: ['cave'], evolvesTo: [444] },
  { id: 444, rarity: 'A', courses: ['cave'], evolvesTo: [445] },
  { id: 445, rarity: 'S', courses: ['cave'] },
  { id: 447, rarity: 'B', courses: ['cave'], evolvesTo: [448] },
  { id: 448, rarity: 'S', courses: ['cave'] },
  { id: 483, rarity: 'SS', courses: ['legend'] },
  { id: 484, rarity: 'SS', courses: ['legend'] },
  { id: 487, rarity: 'SS', courses: ['legend'] },
  { id: 491, rarity: 'SS', courses: ['legend'] },

  // ===== 5세대 =====
  { id: 495, rarity: 'C', courses: ['grass'], evolvesTo: [496] },
  { id: 496, rarity: 'B', courses: ['grass'], evolvesTo: [497] },
  { id: 497, rarity: 'A', courses: ['grass'] },
  { id: 498, rarity: 'C', courses: ['cave'], evolvesTo: [499] },
  { id: 499, rarity: 'B', courses: ['cave'], evolvesTo: [500] },
  { id: 500, rarity: 'A', courses: ['cave'] },
  { id: 501, rarity: 'C', courses: ['sea'], evolvesTo: [502] },
  { id: 502, rarity: 'B', courses: ['sea'], evolvesTo: [503] },
  { id: 503, rarity: 'A', courses: ['sea'] },
  { id: 570, rarity: 'B', courses: ['cave'], evolvesTo: [571] },
  { id: 571, rarity: 'S', courses: ['cave'] },
  { id: 610, rarity: 'B', courses: ['cave'], evolvesTo: [611] },
  { id: 611, rarity: 'A', courses: ['cave'], evolvesTo: [612] },
  { id: 612, rarity: 'S', courses: ['cave'] },
  { id: 643, rarity: 'SS', courses: ['legend'] },
  { id: 644, rarity: 'SS', courses: ['legend'] },

  // ===== 6세대 =====
  { id: 656, rarity: 'C', courses: ['sea'], evolvesTo: [657] },
  { id: 657, rarity: 'B', courses: ['sea'], evolvesTo: [658] },
  { id: 658, rarity: 'S', courses: ['sea'] },

  // ===== 7세대 =====
  { id: 722, rarity: 'C', courses: ['grass'], evolvesTo: [723] },
  { id: 723, rarity: 'B', courses: ['grass'], evolvesTo: [724] },
  { id: 724, rarity: 'A', courses: ['grass'] },
  { id: 725, rarity: 'C', courses: ['cave'], evolvesTo: [726] },
  { id: 726, rarity: 'B', courses: ['cave'], evolvesTo: [727] },
  { id: 727, rarity: 'S', courses: ['cave'] },
  { id: 728, rarity: 'C', courses: ['sea'], evolvesTo: [729] },
  { id: 729, rarity: 'B', courses: ['sea'], evolvesTo: [730] },
  { id: 730, rarity: 'A', courses: ['sea'] },
  { id: 778, rarity: 'S', courses: ['cave'] },
  { id: 791, rarity: 'SS', courses: ['legend'] },
  { id: 792, rarity: 'SS', courses: ['legend'] },

  // ===== 8세대 =====
  { id: 810, rarity: 'C', courses: ['grass'], evolvesTo: [811] },
  { id: 811, rarity: 'B', courses: ['grass'], evolvesTo: [812] },
  { id: 812, rarity: 'A', courses: ['grass'] },
  { id: 813, rarity: 'C', courses: ['cave'], evolvesTo: [814] },
  { id: 814, rarity: 'B', courses: ['cave'], evolvesTo: [815] },
  { id: 815, rarity: 'S', courses: ['cave'] },
  { id: 816, rarity: 'C', courses: ['sea'], evolvesTo: [817] },
  { id: 817, rarity: 'B', courses: ['sea'], evolvesTo: [818] },
  { id: 818, rarity: 'A', courses: ['sea'] },
  { id: 823, rarity: 'A', courses: ['grass'] },
  { id: 831, rarity: 'C', courses: ['grass'], evolvesTo: [832] },
  { id: 832, rarity: 'B', courses: ['grass'] },
  { id: 885, rarity: 'B', courses: ['cave'], evolvesTo: [886] },
  { id: 886, rarity: 'A', courses: ['cave'], evolvesTo: [887] },
  { id: 887, rarity: 'S', courses: ['cave'] },
  { id: 888, rarity: 'SS', courses: ['legend'] },
  { id: 889, rarity: 'SS', courses: ['legend'] },
];
